[package]
name = "varint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.164"

[dev-dependencies]
bincode = "1.3.3"
serde_json = "1.0.97"
